services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - ./config:/config
      - ${SSD1_PATH}/tvseries:/tv
      - ${SSD1_PATH}/torrent/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

