services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_HOST}
      PUID: 1000 # optional, your user id
      PGID: 1000 # optional, your group id
      HOMEPAGE_VAR_SSD1_DRIVE: ${SSD1_DRIVE}
      HOMEPAGE_VAR_SERVER_IP: ${IP}
      # Active services
      HOMEPAGE_VAR_WGEASY_IP: ${WGEASY_IP}
      HOMEPAGE_VAR_WGEASY_URL: ${WGEASY_URL}
      HOMEPAGE_VAR_VAULTWARDEN_IP: ${VAULTWARDEN_IP}
      HOMEPAGE_VAR_VAULTWARDEN_URL: ${VAULTWARDEN_URL}
      HOMEPAGE_VAR_KUMA_IP: ${KUMA_IP}
      HOMEPAGE_VAR_KUMA_URL: ${KUMA_URL}
      HOMEPAGE_VAR_KUMA_SLUG: ${KUMA_SLUG}
      HOMEPAGE_VAR_SOUNDVAULT_URL: ${SOUNDVAULT_URL}
      HOMEPAGE_VAR_NPM_IP: ${NPM_IP}
      HOMEPAGE_VAR_NPM_URL: ${NPM_URL}
      HOMEPAGE_VAR_NPM_USERNAME: ${NPM_USERNAME}
      HOMEPAGE_VAR_NPM_PASSWORD: ${NPM_PASSWORD}
      HOMEPAGE_VAR_PIHOLE_IP: ${PIHOLE_IP}
      HOMEPAGE_VAR_PIHOLE_URL: ${PIHOLE_URL}
      HOMEPAGE_VAR_PIHOLE_PASSWORD: ${PIHOLE_PASSWORD}
      HOMEPAGE_VAR_N100_IP: ${N100_IP}
      HOMEPAGE_VAR_GLANCES_RPI4_URL: ${GLANCES_RPI4_URL}
      HOMEPAGE_VAR_GLANCES_N100_URL: ${GLANCES_N100_URL}
      HOMEPAGE_VAR_IMMICH_IP: ${IMMICH_IP}
      HOMEPAGE_VAR_IMMICH_URL: ${IMMICH_URL}
      HOMEPAGE_VAR_IMMICH_API_KEY: ${IMMICH_API_KEY}

    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./config/images:/app/public/images
      - ./config/icons:/app/public/icons
      - ${SSD1_DRIVE}:/mnt/ssd1:ro
    restart: unless-stopped

  dockerproxy-rpi4:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy-rpi4
    environment:
      - CONTAINERS=1 # allow reading container info
      - POST=0       # disable write operations (read-only)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
