services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - ./config:/config
      - ${SSD1_PATH}/movies:/movies
      - ${SSD1_PATH}/torrent/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

