---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

favicon: /icons/favicon-32x32.png

background:
  image: /images/cyberpunk-edgerunners.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

pages:
  - name: Home
  - name: Monitoring
    icon: mdi-chart-line

layout:
  Music:
    tab: Home
    style: row
    columns: 1
    header: false
  Photos:
    tab: Home
  Dev Tools:
    tab: Home
    style: column
    columns: 5
  RPi4:
    tab: Monitoring
    style: row
    columns: 1
    header: false
  RPi4-Stats:
    tab: Monitoring
    style: row
    columns: 5
    header: false
  N100:
    tab: Monitoring
    style: row
    columns: 1
    header: false
  N100-Stats:
    tab: Monitoring
    style: row
    columns: 4
    header: false
