include:
  - homepage/docker-compose.yml
  - nginx-proxy-manager/docker-compose.yml
  - pihole/docker-compose.yml
  - vaultwarden/docker-compose.yml
  - uptime-kuma/docker-compose.yml
  - wg-easy/docker-compose.yml
  - sound-vault/docker-compose.yml

