---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

background:
  image: /images/cyberpunk-edgerunners.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
